format_version: 3
environments:
  generic:
    environment_variables:
      DOCKER_TAG: latest
      DOCKER_NO_CACHE: false
      DOCKER_BUILD_LOCAL: true
      DOCKER_REGISTRY_INSECURE: true
    pipelines:
      - uplain-init
      - pip3-dev
      - cv-dev
      - cv-bazel-dev
      - cv-tf-jupyter-dev.1.12.0
      - cv-cuda92
      - cv-cudnn92
      - cv-nccl92-tf-jupyter-dev.1.12.0
      - cv-nccl92-tf-jupyter-dev.broadwell_1.12.0
      - cv-nccl92-tf-jupyter-dev.nvcap37_1.12.0
      - cv-nccl92-tf-jupyter-dev.nvcap52_1.12.0
      - cv-nccl92-tf-jupyter-dev.broadwell_nvcap37_1.12.0
      - cv-nccl92-tf-jupyter-dev.broadwell_nvcap52_1.12.0
      - cv-tf.1.12.0
      - cv-tf-jupyter.1.12.0
  performance:
    environment_variables:
      DOCKER_TAG: latest
      DOCKER_NO_CACHE: false
      DOCKER_BUILD_LOCAL: true
      DOCKER_REGISTRY_INSECURE: true
    pipelines:
      - cv-tf-dev.1.12.0
      - cv-nccl92
      - cv-nccl92.broadwell
      - cv-nccl92.nvcap52
      - cv-nccl92.broadwell_nvcap52
      - cv-nccl92.nvcap37
      - cv-nccl92.broadwell_nvcap37
      - cv-nccl92-tf-dev.1.12.0
      - cv-nccl92-tf-dev.broadwell_1.12.0
      - cv-nccl92-tf-dev.nvcap52_1.12.0
      - cv-nccl92-tf-dev.broadwell_nvcap52_1.12.0
      - cv-nccl92-tf-dev.nvcap37_1.12.0
      - cv-nccl92-tf-dev.broadwell_nvcap37_1.12.0
